from typing import Literal

from supabase import Client
from app.config import get_supabase_admin_client
from app.auth.schemas import InviteClinicianRequest, InvitePatientRequest, InviteResponse


RoleType = Literal["clinician", "patient"]


class AuthService:
    def __init__(self, admin_client: Client | None = None) -> None:
        # Use service-role client; bypasses RLS for admin operations
        self.admin: Client = admin_client or get_supabase_admin_client()

    def _create_user_with_role(self, email: str, role: RoleType) -> str:
        """
        Create a Supabase auth user with app_metadata.role set.
        Returns the auth user id as string.
        """
        # Generate a temporary random password; user will reset via email if needed.
        import secrets
        temp_password = secrets.token_urlsafe(16)

        # Supabase Python client: auth.admin.create_user(...)
        # Adjust to actual client version if needed.
        resp = self.admin.auth.admin.create_user(
            {
                "email": email,
                "password": temp_password,
                "email_confirm": False,
                "user_metadata": {},
                "app_metadata": {"role": role},
            }
        )

        
        if not resp.user:
            raise RuntimeError("Failed to create auth user")

        return str(resp.user.id)

    def invite_clinician(self, payload: InviteClinicianRequest) -> InviteResponse:
        """
        1) Create auth user with role=clinician
        2) Insert into clinicians table
        """
        user_id = self._create_user_with_role(payload.email, "clinician")

        # Insert clinician profile
        self.admin.table("clinicians").insert(
            {
                "clinician_id": user_id,
                "email": payload.email,
                "full_name": payload.full_name,
                "specialty": payload.specialty,
                "is_active": True,
            }
        ).execute()

        return InviteResponse(user_id=user_id, email=payload.email, role="clinician")

    def invite_patient(self, payload: InvitePatientRequest) -> InviteResponse:
        """
        1) Create auth user with role=patient
        2) Create patients row
        3) Create patient_accounts row linking auth user to patient_id
        """
        user_id = self._create_user_with_role(payload.email, "patient")

        # Create patient record
        patients_res = self.admin.table("patients").insert(
            {
                # patient_id will be generated by DB default if you set it that way;
                # otherwise supply uuid here.
                "assigned_model_id": None,
                "primary_clinician_id": None,
            }
        ).execute()

        if not patients_res.data:
            raise RuntimeError("Failed to create patient record")
        patient_row = patients_res.data[0]
        patient_id = patient_row["patient_id"]

        # Link auth user to patient id
        self.admin.table("patient_accounts").insert(
            {
                "user_id": user_id,
                "patient_id": patient_id,
            }
        ).execute()

        # Optional: if you later add identity fields to patients, update here

        return InviteResponse(user_id=user_id, email=payload.email, role="patient")
